artifact_location: /home/shujaat_tracebloc/open_source/MLOPS_continuous_improvement_explainability/notebooks/../mlflow/387597982808446599
creation_time: 1742559930842
experiment_id: '387597982808446599'
last_update_time: 1742559930842
lifecycle_stage: active
name: fashion-mnist
